import json

def plan(c): return f'''Create a personalized learning plan for topic={c.topic}, level={c.level}, language={c.language}, difficulty={c.difficulty}. Requested sections={c.sections}; quiz questions={c.num_questions}. Extra={c.extra_instructions or "None"}. Return ONLY JSON with learning_goal, learner_profile, subtopics, prerequisites, priority_concepts, recommended_sequence, content_strategy, assessment_strategy.'''
def content(c): return f'''Create study content using this plan: {json.dumps(c.plan,ensure_ascii=False)}. Topic={c.topic}; level={c.level}; language={c.language}; difficulty={c.difficulty}; requested={c.sections}. Do not create quiz questions. Return ONLY JSON with title, summary, key_points, flashcards (front/back), examples.'''
def assessment(c): return f'''Create exactly {c.num_questions} MCQs from this plan and content. Plan={json.dumps(c.plan,ensure_ascii=False)} Content={json.dumps(c.content,ensure_ascii=False)} Difficulty={c.difficulty}. Each question needs exactly 4 options, one answer matching an option, explanation, tested_concept and difficulty. Return ONLY JSON with quiz and assessment_coverage.'''
def review(c): return f'''Strictly review this study pack. Plan={json.dumps(c.plan,ensure_ascii=False)} Content={json.dumps(c.content,ensure_ascii=False)} Assessment={json.dumps(c.assessment,ensure_ascii=False)}. Check accuracy, alignment, coverage, personalization, clarity and quiz correctness. Return ONLY JSON with overall_quality, accuracy_issues, personalization_issues, coverage_issues, assessment_issues, clarity_issues, required_changes, approved.'''
def refine(c): return f'''Create the FINAL study pack using plan={json.dumps(c.plan,ensure_ascii=False)}, content={json.dumps(c.content,ensure_ascii=False)}, assessment={json.dumps(c.assessment,ensure_ascii=False)}, reviewer_feedback={json.dumps(c.review,ensure_ascii=False)}. User: topic={c.topic}, level={c.level}, language={c.language}, difficulty={c.difficulty}, requested={c.sections}. Fix all reviewer issues. Produce exactly {c.num_questions} MCQs, each with 4 options and answer matching an option. Return ONLY JSON with title, summary, key_points, flashcards, examples, quiz, study_tips.'''

SYSTEM = "You are a precise educational AI. Return only valid JSON."
